### ISSUE TITLE
Using # in the color values?

### ISSUE THREAD

**Issue by michaelroper** [AndreaMinato/tailwind-heropatterns#1]
Hey Andrea - this plugin works great, thanks so much! 👍 

I had a bit of trouble getting it going, because I was trying to define my colors like below, to use the color values already defined earlier in my tailwind config:
```
colors: {
    default: colors['blue-lighter'],
    'green': colors['green-lighter']
},
```
... but those color values include the `#` in them, like `'blue-lighter' : '#99D9F8'`.

In the patterns.js file, you already have the `#` encoded as `%23` - do you think it would be possible to remove that from being hardcoded in the URI, and instead just encode the `#` before you replace the `FILLCOLOR`? 

That would make it easier to define colors either from the TW colors object, or as a custom color like `#FF00FF`... 

Hope that all made sense?

**Comment by AndreaMinato** [comment]
Hi @michaelroper

It makes perfect sense. Unfortunately the background-image does not work with `#` 

Now in the addUtilities the `#` will be replaced with `%23` so it will work.
```js
 color = color.replace("#", "%23");
```

Now it also works with rgb colors.

Thanks for pointing this out.

**Comment by michaelroper** [comment]
Perfect! Though you forgot to take out the `%23`'s already in the patterns.js file, so now it's doubling up, like `fill='%23%23ff00ff'`...

**Comment by michaelroper** [comment]
Never mind, looks like you beat me to that too! :)

**Comment by AndreaMinato** [comment]
It was a mistake in the staging area.
I'm forcing myself to use the git cli, sorry about that

**Comment by danieledistanio** [comment]
Hi Andrea,

first, thanks, this is a very handy plugin!

Only problem it still outputs colors in fill='%2319062d' format.

Using Tailwind 2
