### ISSUE TITLE
How to adjust size of patterns?

### ISSUE THREAD

**Issue by Ashvith10** [AndreaMinato/tailwind-heropatterns#9]
I would like to adjust the size of the polka dots, but it looks like there's no way to do the same?

**Comment by AndreaMinato** [comment]
Hi, I'm sorry but i don't quite understand what you mean by adjust the size of a pattern.
how would you do it with just heropatterns?

**Comment by Ashvith10** [comment]
@AndreaMinato currently, the polka dots are way too big, so I was wondering if there's any way to reduce the size.
